# Generated by Django 3.1 on 2020-11-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='std',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('fname', models.CharField(default='', max_length=10)),
                ('lname', models.CharField(default='', max_length=10)),
                ('pass1', models.CharField(default='', max_length=10)),
                ('std_phone_num', models.CharField(default='', max_length=10)),
                ('parent_phone_num', models.CharField(default='', max_length=10)),
                ('parent_name', models.CharField(default='', max_length=10)),
                ('parent_password', models.CharField(default='', max_length=10)),
                ('unique_id', models.CharField(default='', max_length=8)),
                ('room', models.CharField(default='A', max_length=1)),
                ('kebele', models.CharField(choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04')], default=4, max_length=1)),
                ('gender', models.CharField(choices=[('m', 'M'), ('f', 'F')], default='m', max_length=1)),
                ('grade', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='12', max_length=2)),
                ('age', models.IntegerField(default=16)),
                ('pass2', models.CharField(default='', max_length=10)),
                ('os', models.CharField(default='', max_length=140)),
                ('code', models.CharField(default='', max_length=6)),
                ('admin_type', models.CharField(default='stude', max_length=5)),
                ('view_counter', models.IntegerField(default=1)),
                ('no_forget', models.IntegerField(default=0)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
