# Generated by Django 3.1 on 2020-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='std',
            name='pass2',
        ),
        migrations.AlterField(
            model_name='std',
            name='pass1',
            field=models.CharField(default='', max_length=20),
        ),
    ]
