# Generated by Django 3.1 on 2020-12-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201209_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='unique_id',
            field=models.CharField(default='', max_length=31),
        ),
    ]
