# Generated by Django 3.1 on 2020-12-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201209_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='parent_password',
            field=models.CharField(default='', max_length=35),
        ),
    ]
