# Generated by Django 3.1 on 2020-12-31 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201231_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('fname', models.CharField(default='', max_length=10)),
                ('lname', models.CharField(default='', max_length=10)),
                ('subject', models.CharField(default='', max_length=10)),
                ('grade', models.CharField(default='', max_length=10)),
                ('room', models.CharField(default='', max_length=10)),
                ('all_class', models.CharField(default='', max_length=10)),
                ('unique_id', models.CharField(default='', max_length=10)),
                ('pass1', models.CharField(default='', max_length=20)),
                ('std_phone_num', models.CharField(default='', max_length=10)),
                ('os', models.CharField(default='', max_length=140)),
                ('admin_type', models.CharField(default='teach', max_length=5)),
                ('view_counter', models.IntegerField(default=1)),
                ('no_forget', models.IntegerField(default=0)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='std',
            name='code',
        ),
        migrations.CreateModel(
            name='mark_ict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten1', models.CharField(default=5, max_length=3)),
                ('ten2', models.CharField(default=5, max_length=3)),
                ('ten3', models.CharField(default=5, max_length=3)),
                ('twenty', models.CharField(default=5, max_length=3)),
                ('fiftiy', models.CharField(default=5, max_length=3)),
                ('hundred', models.CharField(default=5, max_length=3)),
                ('std_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.std')),
            ],
        ),
    ]
