# Generated by Django 3.1 on 2020-12-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201231_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark_ict',
            old_name='fiftiy',
            new_name='fifty',
        ),
    ]
